### ISSUE TITLE
Translation of error set because of error is incorrect

### ISSUE THREAD

**Issue by guiraldelli** [SAFE-eV/transparenzsoftware#12]
The string for error because of error measurements is [incorrectly translated to English](https://github.com/SAFE-eV/transparenzsoftware/blob/master/src/main/resources/i18n/lang.properties#L213). Please [compare it with the German version](https://github.com/SAFE-eV/transparenzsoftware/blob/master/src/main/resources/i18n/lang_de_DE.properties#L216).

This is reflected in the GUI, as can be seen below:
![image](https://user-images.githubusercontent.com/530790/105990561-f23d3c80-60a2-11eb-8873-e381b227f401.png)

**Comment by jdo-geek** [comment]
Fixed already in 1.2.0
