### ISSUE TITLE
Please add an open source license

### ISSUE THREAD

**Issue by ahzf** [SAFE-eV/transparenzsoftware#2]
Please add an open source license, without this software is de-facto closed source.

**Comment by wm-mjovic** [comment]
License review is already in progress and will be added ASAP.

**Comment by byt3pool** [comment]
@wm-mjovic Is there any new update on this?

**Comment by ahzf** [comment]
Any news on this?

**Comment by uap-universe** [comment]
@wm-mjovic we need to align our understanding of the meaning of the term ASAP ;-)

**Comment by wm-mjovic** [comment]
@byt3pool @ahzf @uap-universe The issue has been addressed by me several times within the alliance as soon as it was brought up, however as this is a collaborative work a decision had to be made also by the alliance as a whole.

I am not officially holding the mandate for this within the alliance anymore (for quite a lot of time already) but I'll try to get in touch with someone responsible for this matter. To be honest, I am quite surprised by myself that this has not been resolved until now ... so thanks for bringing it up.

**Comment by jdo-geek** [comment]
Please see LICENSE file.
