### ISSUE TITLE
Example XML does not validate.

### ISSUE THREAD

**Issue by uap-universe** [SAFE-eV/transparenzsoftware#29]
The [example](https://github.com/SAFE-eV/transparenzsoftware/blob/master/XML_Format.md) shows the following XML:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<values>
   <value transactionId="1" context="Transaction.Begin">
      <signedData format="OCMF" encoding="plain" transactionId="29">OCMF|{"FV":"1.0","GI":"KEBA_KCP30","GS":"17619300","GV":"2.8.5","PG":"T32","IS":false,"IL":"NONE","IF":["RFID_NONE","OCPP_NONE","ISO15118_NONE","PLMN_NONE"],"IT":"NONE","ID":"","RD":[{"TM":"2019-08-13T10:03:15,000+0000 I","TX":"B","EF":"","ST":"G","RV":0.2596,"RI":"1-b:1.8.0","RU":"kWh"},{"TM":"2019-08-13T10:03:36,000+0000 R","TX":"E","EF":"","ST":"G","RV":0.2597,"RI":"1-b:1.8.0","RU":"kWh"}]}|{"SD":"304502200E2F107C987A300AC1695CA89EA149A8CDFA16188AF0A33EE64B67964AA943F9022100889A72B6D65364BEA8562E7F6A0253157ACFF84FE4929A93B5964D23C4265699"}</signedData>
        <publicKey encoding="hex">3059301306072A8648CE3D020106082A8648CE3D030107034200043AEEB45C392357820A58FDFB0857BD77ADA31585C61C430531DFA53B440AFBFDD95AC887C658EA55260F808F55CA948DF235C2108A0D6DC7D4AB1A5E1A7955BE</publicKey>
    </value>
</values>
```

But that XML is invalid according to the [XSD](https://github.com/SAFE-eV/transparenzsoftware/blob/master/src/main/java/com/hastobe/transparenzsoftware/verification/xml/xsd/values.xsd).

The context "Transaction.Begin" does not exist, it has to be Transaction.Start" according to the schema. But to be honest, I think the schema is wrong here, if it is supposed to match the OCPP reading context.

Additionally, the `signedData` element has an attribute `transactionId` in the example that is not specified in the schema.

And finally, the elements `signedData` and `publicKey` are in the wrong order in the example. `publicKey` must come first and then `signedData`.

**Comment by ahzf** [comment]
Well... I would say, that always the XSD is wrong... because it does not make much sense to define a sequence of elements, when there is just one element, and a sequence of two elements, when one is optional and while there are two more elements outside this sequence. From a domain perspective the public key should be optional anyway, as it is against good security practice to send the public key on the same channel like the signed data.

**Comment by jdo-geek** [comment]
Removed bogus *.xsd files. The right files are in the src/main/resources directory.
