### ISSUE TITLE
Transparency Software does not validate dataset when Errorflag "t" is set

### ISSUE THREAD

**Issue by eSysAlex** [SAFE-eV/transparenzsoftware#31]
Issue:
If we check a OCMF dataset with error flag "EF":"t" for time error is set, Transparency software denies to validate correct OCMF dataset.

Context:
The OCMF dataset was created in a charging session, where a power outage happened. The Charging session was correctly resumed and measured after power was regained, but the EF flag "t" was set to inform that the time values of the dataset can no longer be used for session time calculation. However the values for energy amount are valid.

Expectation:
The user is still informed that there was an error with the time calculation, but the validation is still done and gets a green tickmark, as the energy value is correct and the full dataset is correctly signed by the crypto key of the energy meter.

**Comment by jdo-geek** [comment]
Do you have an example file to reproduce the problem?

**Comment by eSysAlex** [comment]
[OCMF_meter_readings_EF_t.zip](https://github.com/SAFE-eV/transparenzsoftware/files/11452108/OCMF_meter_readings_EF_t.zip)

This is an example OCMF file giving the error with v1.2.0

**Comment by jdo-geek** [comment]
Fixed in 1.3.1
