### ISSUE TITLE
Should publish artifacts for dependency project

### ISSUE THREAD

**Issue by evc-erik** [SAFE-eV/transparenzsoftware#32]
Since commit 0b92601 the project cannot be built due to an unresolved dependency:

```
[ERROR] Failed to execute goal on project de.safe_ev.transparenzsoftware: Could not resolve dependencies for project de.safe_ev:de.safe_ev.transparenzsoftware:jar:1.3.0: The following artifacts could not be resolved: com.metabit.custom.safe:safesealing:jar:0.7.1-SNAPSHOT (absent): Could not find artifact com.metabit.custom.safe:safesealing:jar:0.7.1-SNAPSHOT -> [Help 1]
```

**Comment by evc-erik** [comment]
I just discovered the source for the dependency here: https://github.com/SAFE-eV/SAFESealing and I'm able to build, now. This should really be published as an artifact somewhere. Maybe [GitHub Packages](https://github.com/features/packages)?

**Comment by Zenahr** [comment]
agreed, this would simplify things greatly as we are running into issues building the binary.

**Comment by jdo-geek** [comment]
This topic was added to the README.md

**Comment by Zenahr** [comment]
@jdo-geek I don't see it being mentioned, but maybe that's just me.

**Comment by Zenahr** [comment]
also fyi the link is broken:
![image](https://github.com/SAFE-eV/transparenzsoftware/assets/47085752/adf67e74-5405-4b94-a772-5b1c1b993da5)
