### ISSUE TITLE
Download file on website has incorrect SHA265 checksum

### ISSUE THREAD

**Issue by bkonetzny** [SAFE-eV/transparenzsoftware#34]
Seems https://safe-ev.org/de/transparenzsoftware/e-mobilist/ got redesigned and the download target of transparenzsoftware 1.2 changed from https://www.safe-ev.de/global/downloads/transparenzsoftware-1.2.0.jar to https://safe-ev.org/files/software/transparenzsoftware-1.2.0.jar - this seemingly did also change the checksum, which is supposed to be `ecabb8b29eaa6a3e51c8491f43ce4a112dacdc74016e2129804aa368fdc0faf5` but doesn't work anymore with the new download location, as this returns a file with checksum `890d4ea7841e7b5105ccabb53ac2056ba40041d1bd37c685d44f4745db4af59d` now.

**Comment by jdo-geek** [comment]
This has been checked and adjusted.
