### ISSUE TITLE
Missing Release for Version 1.3

### ISSUE THREAD

**Issue by juocal** [SAFE-eV/transparenzsoftware#36]
It has come to my attention that there is a discrepancy in the release status of version 1.3 on the project's GitHub repository. Despite the presence of a new release on the official website, the corresponding release is not listed on GitHub.

There is even a tag (see https://github.com/SAFE-eV/transparenzsoftware/releases/tag/v1.3.0-rc1) and a development branch for the new Version 1.3 (see https://github.com/SAFE-eV/transparenzsoftware/tree/BugFix-1.3.0-rc1)

This issue may cause confusion among users who rely on the GitHub repository for release information. It would be greatly appreciated if this matter could be addressed and the release for version 1.3 added to the GitHub release list.

**Comment by jdo-geek** [comment]
Hi Juocal,
Just pushed the final 1.3.0 Version.
