### ISSUE TITLE
do current version of transparanz tool support ecdsa-secp256

### ISSUE THREAD

**Issue by Vishalsinh-Parmar** [SAFE-eV/transparenzsoftware#44]
Hi SafeEV team,
I have got requirement from client that my EV charger should verify billdata with your GUI Transparanz tool. I wanted to know if transparanz tool support data signed by ecc Nist-P256 Private key?

PS: I am using optiga trust m for key genration and sign bill data. minimum ecc curve it can genrate is "elliptic curve key based on NIST P256"

**Comment by jdo-geek** [comment]
Hello,
please send this kind of questions to info@safe-ev.de
It is not so simple to answer because it depends on the format you use for the billing data.
Thanks!
